site_name: ObjCrypto 
site_url: https://quicr.github.io/objCrypto
repo_url: https://github.com/Quicr/objCrypto
theme: readthedocs
nav:
    - Overview: index.md
    - API: api.md
    - Building: building.md
markdown_extensions:
    - toc:
        permalink: "#"

